name: Leadership Memes
favicon: null
layout_spectrum: 0.240008746040985
typography_spectrum: 0.6552480526734143
title: Leadership Memes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.32079700706526637
  lightness: 0.896546837175265
  saturation: 0.663723858539015
  rhythmicContrast: 0.2510893407743424
purpose: []
